# global:
#   server: https://kubernetes.default.svc
#   cluster: sigstore-prod

trillian:
  enabled: true
  namespace:
    name: trillian-system
    create: false
  fullnameOverride: trillian
  forceNamespace: trillian-system
  serviceAccountName:
    logServer: trillian-logserver
    logSigner: trillian-logsigner
  logServer:
    enabled: true
    name: logserver
    fullnameOverride: trillian-logserver
    portRPC: 8090
    portHTTP: 8091
    replicaCount: 3
    resources:
      requests:
        memory: "1G"
        cpu: "0.5"
    serviceAccount:
      annotations:
        iam.gke.io/gcp-service-account: sigstore-prod-mysql-sa@oci-signer-service-dev.iam.gserviceaccount.com
    podAnnotations:
      prometheus.io/scrape: "true"
      prometheus.io/path: "/metrics"
      prometheus.io/port: "8091"
    securityContext:
      runAsNonRoot: true
      runAsUser: 65533
  logSigner:
    enabled: true
    name: logsigner
    portRPC: 8090
    portHTTP: 8091
    fullnameOverride: trillian-logsigner
    resources:
      requests:
        memory: "1G"
        cpu: "0.5"
    serviceAccount:
      annotations:
        iam.gke.io/gcp-service-account: sigstore-prod-mysql-sa@oci-signer-service-dev.iam.gserviceaccount.com
    podAnnotations:
      prometheus.io/scrape: "true"
      prometheus.io/path: "/metrics"
      prometheus.io/port: "8091"
    securityContext:
      runAsNonRoot: true
      runAsUser: 65533
  mysql:
    enabled: false
    hostname: localhost
    auth:
      existingSecret: "trillian-mysql"
      username: "trillian"
    gcp:
      enabled: true
      instance: oci-signer-service-dev:us-central1:sigstore-prod-mysql-6553c6dc
      cloudsql:
        version: "1.29.0"
        resources:
          requests:
            memory: "0.5Gi"
            cpu: 0.1
        securityContext:
          runAsNonRoot: true
          runAsUser: 65533
