---
apiVersion: autoscaling/v2beta1
kind: HorizontalPodAutoscaler
metadata:
  name: {{ template "tektonPipelines.fullname". }}-webhook
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: webhook
    app.kubernetes.io/component: webhook
{{ include "tektonPipelines.labels" . | indent 4 }}
    pipeline.tekton.dev/release: {{ .Chart.AppVersion | quote }}
    version: {{ .Chart.AppVersion | quote }}
spec:
  minReplicas: {{ .Values.webhookAutoscaler.minReplicas}}
  maxReplicas: {{ .Values.webhookAutoscaler.maxReplicas }}
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: tekton-pipelines-webhook
  metrics:
    - type: Resource
      resource:
        name: cpu
        targetAverageUtilization: 100
