apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ template "tektonPipelines.fullname". }}-controller-leaderelection
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/component: controller
{{ include "tektonPipelines.labels" . | indent 4 }}
subjects:
  - kind: ServiceAccount
    name: {{ template "tektonPipelines.fullname". }}-controller
    namespace: {{ .Release.Namespace }}
roleRef:
  kind: Role
  name: {{ template "tektonPipelines.fullname". }}-leader-election
  apiGroup: rbac.authorization.k8s.io
