apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "tektonPipelines.fullname". }}-controller
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/component: controller
{{ include "tektonPipelines.labels" . | indent 4 }}

