apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "tektonPipelines.fullname". }}-webhook
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/component: webhook
{{ include "tektonPipelines.labels" . | indent 4 }}
