icon: https://github.com/tektoncd/chains/blob/main/tekton_chains-color.png

chainsDeployment:
  replicas: 1
  image:
    repository: "gcr.io/tekton-releases/github.com/tektoncd/chains/cmd/controller"
    tag: "v0.8.0"
    digest: "sha256:599b81739a1171874ee506c314686ff854c64b909df80d9ed558ccce115cee95"

tenantLogging:
  # Common configuration for all knative codebase
  zap-logger-config: |
    {
      "level": "info",
      "development": false,
      "sampling": {
        "initial": 100,
        "thereafter": 100
      },
      "outputPaths": ["stdout"],
      "errorOutputPaths": ["stderr"],
      "encoding": "json",
      "encoderConfig": {
        "timeKey": "ts",
        "levelKey": "level",
        "nameKey": "logger",
        "callerKey": "caller",
        "messageKey": "msg",
        "stacktraceKey": "stacktrace",
        "lineEnding": "",
        "levelEncoder": "",
        "timeEncoder": "iso8601",
        "durationEncoder": "",
        "callerEncoder": ""
      }
    }
  # Log level overrides
  loglevel.controller: "info"
  loglevel.webhook: "info"

tenantConfig:
  artifacts.taskrun.format: tekton
  artifacts.taskrun.storage: tekton
  artifacts.taskrun.signer: x509
  artifacts.oci.storage: oci
  artifacts.oci.format: simplesigning
  artifacts.oci.signer: x509
