apiVersion: batch/v1
kind: Job
metadata:
  name: createdb
  namespace: trillian-system
spec:
  template:
    spec:
      serviceAccountName: trillian-logsigner
      restartPolicy: Never
      containers:
      - name: createdb
        # This image was built via `ko publish` in the `sigstore/scaffolding` repo
        image: gcr.io/oci-signer-service-dev/createdb@sha256:e1ca4dc4a4e177e8f6f828bb76b5218baf72743126c610ba482309050bb27fc0
        args: [
        "--mysql_uri=$(MYSQL_USER):$(MYSQL_PASSWORD)@tcp(localhost:3306)/",
        "--db_name=trillian"
        ]
        env:
          - name: DATABASE_NAME
            valueFrom:
              secretKeyRef:
                name: trillian-mysql 
                key: mysql-database
          - name: MYSQL_USER
            valueFrom:
              secretKeyRef:
                name: trillian-mysql 
                key: mysql-user
          - name: MYSQL_PASSWORD
            valueFrom:
              secretKeyRef:
                name: trillian-mysql 
                key: mysql-password
      - name: cloud-sql-proxy
        image: gcr.io/cloudsql-docker/gce-proxy:1.29.0
        command:
          - "/cloud_sql_proxy"
          - "-instances=oci-signer-service-dev:us-central1:sigstore-prod-mysql-992c72f2=tcp:3306"
        securityContext:
          allowPrivilegeEscalation: false
          readOnlyRootFilesystem: true
          runAsNonRoot: true
          capabilities:
            drop:
            - all

