apiVersion: batch/v1
kind: Job
metadata:
  name: createdb
  namespace: trillian-system
spec:
  template:
    spec:
      serviceAccountName: createdb
      restartPolicy: Never
      containers:
      - name: cloud-sql-proxy
        image: gcr.io/cloudsql-docker/gce-proxy:1.29
        command:
          - "/cloud_sql_proxy"
          - "-instances=$(CLOUD_SQL_CONNECTION)"
        env:
        - name: CLOUD_SQL_CONNECTION
          valueFrom:
            configMapKeyRef:
              name: cloud-sql
              key: connection
      - name: createdb
        image: gcr.io/priya-chainguard/createdb@sha256:e1ca4dc4a4e177e8f6f828bb76b5218baf72743126c610ba482309050bb27fc0
        args: [
        "--mysql_uri=$(MYSQL_USER):$(MYSQL_PASSWORD)@tcp($(DATABASE_HOSTNAME):3306)/",
        "--db_name=trillian"
        ]
        env:
          - name: DATABASE_NAME
            valueFrom:
              secretKeyRef:
                name: trillian-client
                key: name
          - name: MYSQL_USER
            valueFrom:
              secretKeyRef:
                name: trillian-client
                key: username
          - name: MYSQL_PASSWORD
            valueFrom:
              secretKeyRef:
                name: trillian-client
                key: password
          - name: DATABASE_HOSTNAME
            valueFrom:
              secretKeyRef:
                name: trillian-client
                key: host
