---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "tektonChains.fullname". }}-tenant-logging
  namespace: {{ .Release.Namespace }}
  labels:
{{ include "tektonChains.labels" . | indent 4 }}
data:
  {{- range $key, $val := .Values.tenantLogging }}
  {{ $key }}: {{ $val | quote }}
  {{- end }}
