apiVersion: apps/v1
kind: Deployment
metadata:
  name: tekton-chains-controller
  namespace: tekton-chains
  labels:
    app.kubernetes.io/name: tekton-pipelines
    app.kubernetes.io/component: chains
    pipeline.tekton.dev/release: "devel"
    version: {{ .Chart.AppVersion | quote }}
    helm-release: {{ .Release.Name | quote }}
    helm.sh/chart: "{{ .Chart.Name }}-{{ .Chart.Version}}"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tekton-chains-controller
  template:
    metadata:
      annotations:
        cluster-autoscaler.kubernetes.io/safe-to-evict: "false"
      labels:
        helm-release: {{ .Release.Name | quote }}
        helm.sh/chart: "{{ .Chart.Name }}-{{ .Chart.Version}}"
        app: tekton-chains-controller
        app.kubernetes.io/name: tekton-pipelines
        app.kubernetes.io/component: controller
        version: {{ .Chart.AppVersion | quote }}
    spec:
      serviceAccountName: {{ template "tektonChains.fullname" . }}-controller
      containers:
        - name: tekton-chains-controller
          image: {{ template "tektonChains.image" .Values.chainsDeployment.image }}
          volumeMounts:
            - name: signing-secrets
              mountPath: /etc/signing-secrets
            - name: oidc-info
              mountPath: /var/run/sigstore/cosign
          env:
            - name: SYSTEM_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: METRICS_DOMAIN
              value: tekton.dev/chains
      volumes:
        - name: signing-secrets
          secret:
            secretName: signing-secrets
        - name: oidc-info
          projected:
            sources:
              # The "public good" instance supports tokens from EKS and GKE by default.
              # The fulcio URL can also be redirected to an instance that has been
              # configured to accept other issuers as well.  Removing this volume
              # completely will direct chains to use alternate ambient credentials
              # (e.g. GKE workload identity, SPIFFE)
              - serviceAccountToken:
                  path: oidc-token
                  expirationSeconds: 600 # Use as short-lived as possible.
                  audience: sigstore
