---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ template "tektonChains.fullname". }}-leaderelection
  namespace: {{ .Release.Namespace }}
  labels:
{{ include "tektonChains.labels" . | indent 4 }}
subjects:
  - kind: ServiceAccount
    name: {{ template "tektonChains.fullname". }}-controller
    namespace: {{ .Release.Namespace }}
roleRef:
  kind: Role
  name: {{ template "tektonChains.fullname". }}-leader-election
  apiGroup: rbac.authorization.k8s.io

