---
apiVersion: v1
kind: Secret
metadata:
  name: signing-secrets
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/component: chains
    app.kubernetes.io/instance: default
    app.kubernetes.io/part-of: tekton-pipelines
    pipeline.tekton.dev/release: "devel"
    version: {{ .Chart.AppVersion }}

# The data is populated at install time.
# data:
